spring.application.name=gen-ai
spring.ai.openai.chat.options.model=gpt-4o
spring.ai.openai.api-key=${OPEN_API_KEY}
spring.ai.ollama.chat.options.model=deepseek-r1:8b

x-rapidapi.key=${RAPID_API_KEY}
x-rapidapi.host=indian-stock-exchange-api2.p.rapidapi.com
x-rapidapi.url=https://indian-stock-exchange-api2.p.rapidapi.com
